### ISSUE TITLE
Support for unstack

### ISSUE THREAD

**Issue by AzeezIsh** [data-apis/array-api-strict#31]
https://data-apis.org/array-api/latest/API_specification/generated/array_api.unstack.html

I would appreciate if you could update this with an unstack command!

**Comment by asmeurer** [comment]
2023.12 support is tracked at #25. Right now we are blocked on test suite support. 

Perhaps once #30 is completed we can start adding 2023.12 functions piecemeal, since they would be disabled by default. `unstack` should match NumPy so there's little risk in adding it even without test suite support.

**Comment by asmeurer** [comment]
unstack is now implemented. For now you have to enable 2023.12 but in a future version that will be the default. https://data-apis.org/array-api-strict/api.html#array_api_strict.set_array_api_strict_flags
